import React,{useCallback,useEffect,useMemo,useState} from "react";
import type {LessonCalendarItem} from "../../../../../packages/database/src/studentTypes";
import type {PaymentMethod} from "../../../../../packages/database/src/types";
import "./open-payments.css";

function unwrap<T>(result:{success:boolean;data?:T;error?:{message?:string}}):T{if(!result.success)throw new Error(result.error?.message||"הפעולה נכשלה.");return result.data as T;}
const paymentLabels:Record<PaymentMethod,string>={cash:"מזומן",bank_transfer:"העברה בנקאית",bit:"ביט",paybox:"פייבוקס"};
const money=(agorot:number)=>new Intl.NumberFormat("he-IL",{style:"currency",currency:"ILS"}).format(agorot/100);

export function OpenPaymentsScreen(){
 const[items,setItems]=useState<LessonCalendarItem[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[notice,setNotice]=useState(""),[workingId,setWorkingId]=useState<string|null>(null),[methods,setMethods]=useState<Record<string,PaymentMethod>>({});
 const load=useCallback(async()=>{setLoading(true);setError("");try{const to=new Date(),from=new Date();to.setHours(23,59,59,999);from.setFullYear(from.getFullYear()-1);from.setHours(0,0,0,0);const all=unwrap(await window.mkApi.lessons.listCalendar(from.toISOString(),to.toISOString()));setItems(all.filter(x=>x.participant.attendanceStatus==="attended"&&x.participant.paymentStatus==="unpaid"&&x.participant.amountAgorot>0));}catch(e){setError(e instanceof Error?e.message:"לא ניתן לטעון תשלומים פתוחים.")}finally{setLoading(false)}},[]);
 useEffect(()=>{void load()},[load]);
 const total=useMemo(()=>items.reduce((sum,x)=>sum+x.participant.amountAgorot,0),[items]);
 const byStudent=useMemo(()=>{const map=new Map<string,{name:string;count:number;amount:number}>();for(const x of items){const row=map.get(x.student.id)??{name:x.student.displayName,count:0,amount:0};row.count++;row.amount+=x.participant.amountAgorot;map.set(x.student.id,row)}return [...map.values()].sort((a,b)=>b.amount-a.amount)},[items]);
 async function markPaid(item:LessonCalendarItem){const method=methods[item.participant.id]??item.participant.paymentMethod??"bit";setWorkingId(item.participant.id);setError("");setNotice("");try{const result=unwrap(await window.mkApi.lessons.updateParticipant(item.participant.id,"attended","paid",method,item.participant.amountAgorot));setNotice(result.receipt?`התשלום סומן וקבלה ${result.receipt.receiptNumber} הופקה אוטומטית.`:"התשלום סומן בהצלחה.");await load()}catch(e){setError(e instanceof Error?e.message:"לא ניתן לסמן את התשלום.")}finally{setWorkingId(null)}}
 return <><header className="page-header"><div><p className="eyebrow">מעקב גבייה</p><h1>תשלומים פתוחים</h1><p>שיעורים שסומנו כהגיעו ועדיין לא שולמו. סימון תשלום מפעיל את מנגנון הקבלה האוטומטית הקיים.</p></div><button className="secondary-button" disabled={loading} onClick={()=>void load()}>{loading?"מרענן…":"רענון"}</button></header>
 <section className="open-payment-stats"><article><span>סה״כ פתוח</span><strong>{money(total)}</strong></article><article><span>מפגשים לתשלום</span><strong>{items.length}</strong></article><article><span>תלמידים עם יתרה</span><strong>{byStudent.length}</strong></article></section>
 {notice&&<p className="success-message">{notice}</p>}{error&&<p className="form-error">{error}</p>}
 {loading?<section className="empty-card"><p>טוענת תשלומים…</p></section>:items.length===0?<section className="empty-card open-payments-empty"><strong>✓ אין כרגע תשלומים פתוחים</strong><p>כל השיעורים שסומנו כהגיעו מסודרים מבחינת תשלום.</p></section>:<><section className="open-payment-students"><h2>סיכום לפי תלמיד</h2><div>{byStudent.map(x=><article key={x.name}><strong>{x.name}</strong><span>{x.count} {x.count===1?"מפגש":"מפגשים"}</span><b>{money(x.amount)}</b></article>)}</div></section><section className="history-table-wrap"><table className="history-table open-payments-table"><thead><tr><th>תלמיד</th><th>מועד השיעור</th><th>שיעור</th><th>סכום</th><th>אמצעי תשלום</th><th>פעולה</th></tr></thead><tbody>{items.map(item=><tr key={item.participant.id}><td><strong>{item.student.displayName}</strong></td><td>{new Intl.DateTimeFormat("he-IL",{dateStyle:"short",timeStyle:"short"}).format(new Date(item.lesson.startsAt))}</td><td>{item.lesson.title}</td><td><strong>{money(item.participant.amountAgorot)}</strong></td><td><select value={methods[item.participant.id]??item.participant.paymentMethod??"bit"} onChange={e=>setMethods(prev=>({...prev,[item.participant.id]:e.target.value as PaymentMethod}))}>{Object.entries(paymentLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></td><td><button className="primary-button compact-payment-button" disabled={workingId===item.participant.id} onClick={()=>void markPaid(item)}>{workingId===item.participant.id?"מפיק קבלה…":"שולם + קבלה"}</button></td></tr>)}</tbody></table></section></>}
 </>;
}
