import type { BusinessSettingsInput, BusinessSettingsRecord, DatabaseHealthReport, IssueReceiptInput, IssueReceiptResult, OnboardingStatus, ReceiptCoreStatus, ReceiptSearchFilters, ReceiptSearchResult,CustomerRecord, CustomerProfile, CustomerCreateInput, CustomerUpdateInput, CustomerDuplicateQuery, CustomerDuplicateMatch, CancelReceiptResult, ReportFilters, DateRangeReport, AnnualReport, BackupOverview, BackupRecord, BackupInspection, RestoreResult, CloudSyncStatus, CloudSyncConnectInput, SupabaseCloudStatus, SupabaseCloudDevice, SupabaseCloudConnectInput, FullHealthReport, ErrorLogRecord, SecurityStatus, DiagnosticPreview, DiagnosticPackageResult, QaReport, QaExportResult, OpenFormatExportResult, SimulatorSubmissionPackageResult, SimulatorOfficialResultInput, SimulatorOfficialResultImport, TaxRegistrationDossierInput, TaxRegistrationDossierResult, ExpenseInput, ExpenseUpdateInput, ExpenseSearchFilters, ExpenseRecord, ExpenseSummary, ReceiptTemplateInput, ReceiptTemplateRecord } from "../../../../packages/database/src/types";
import type { ApiResult } from "../../../../packages/shared/src/api";
import type { AppInfo, AboutInfo } from "../../electron/preload/preload";
declare global { interface Window { mkApi:{
  app:{getInfo():AppInfo;getAbout():Promise<ApiResult<AboutInfo>>;openFolder(kind:"data"|"backups"|"receipts"):Promise<ApiResult<boolean>>;copyTechnicalInfo():Promise<ApiResult<boolean>>;getDiagnosticPreview():Promise<ApiResult<DiagnosticPreview>>;createDiagnosticPackage():Promise<ApiResult<DiagnosticPackageResult|null>>;openDiagnosticsFolder():Promise<ApiResult<boolean>>};
  database:{getHealth():Promise<ApiResult<DatabaseHealthReport>>;getBusinessSettings():Promise<ApiResult<BusinessSettingsRecord|null>>};
  taxOpen:{createRegistrationFixture():Promise<ApiResult<string>>;export(fromDate:string,toDate:string):Promise<ApiResult<OpenFormatExportResult|null>>;createSimulatorPackage(folderPath:string):Promise<ApiResult<SimulatorSubmissionPackageResult>>;saveSimulatorSummaryPdf(submissionFolder:string,input:SimulatorOfficialResultInput):Promise<ApiResult<string|null>>;importSimulatorResult(submissionFolder:string,input:SimulatorOfficialResultInput):Promise<ApiResult<SimulatorOfficialResultImport|null>>;createRegistrationDossier(submissionFolder:string,input:TaxRegistrationDossierInput):Promise<ApiResult<TaxRegistrationDossierResult>>;openFolder(folderPath:string):Promise<ApiResult<boolean>>};
  qa:{run():Promise<ApiResult<QaReport>>;exportReport():Promise<ApiResult<QaExportResult|null>>};
  health:{runFull():Promise<ApiResult<FullHealthReport>>;getSecurityStatus():Promise<ApiResult<SecurityStatus>>};
  errors:{list():Promise<ApiResult<ErrorLogRecord[]>>};
  settings:{getOnboardingStatus():Promise<ApiResult<OnboardingStatus>>;completeSetup(input:BusinessSettingsInput):Promise<ApiResult<BusinessSettingsRecord>>;verifyPin(pin:string):Promise<ApiResult<boolean>>};
  dialogs:{selectImage():Promise<ApiResult<string|null>>;selectFolder():Promise<ApiResult<string|null>>};
  cloudAccount:{getStatus():Promise<ApiResult<SupabaseCloudStatus>>;connect(input:SupabaseCloudConnectInput):Promise<ApiResult<SupabaseCloudStatus>>;disconnect():Promise<ApiResult<SupabaseCloudStatus>>;refresh():Promise<ApiResult<SupabaseCloudStatus>>;listDevices():Promise<ApiResult<SupabaseCloudDevice[]>>;revokeDevice(deviceId:string):Promise<ApiResult<void>>};
  cloudSync:{getStatus():Promise<ApiResult<CloudSyncStatus>>;connect(input:CloudSyncConnectInput):Promise<ApiResult<CloudSyncStatus>>;disconnect():Promise<ApiResult<CloudSyncStatus>>;syncNow():Promise<ApiResult<CloudSyncStatus>>;pull():Promise<ApiResult<CloudSyncStatus>>;forcePush():Promise<ApiResult<CloudSyncStatus>>};
  backups:{getOverview():Promise<ApiResult<BackupOverview>>;create():Promise<ApiResult<BackupRecord|null>>;createGoogleDrive():Promise<ApiResult<BackupRecord>>;createTransfer():Promise<ApiResult<BackupRecord|null>>;inspect():Promise<ApiResult<BackupInspection|null>>;restore():Promise<ApiResult<RestoreResult|null>>;openFolder():Promise<ApiResult<boolean>>};
  reports:{getRange(filters:ReportFilters):Promise<ApiResult<DateRangeReport>>;getAnnual(year:number):Promise<ApiResult<AnnualReport>>;exportCsv(filters:ReportFilters):Promise<ApiResult<string|null>>;exportAccountantPackage(year:number):Promise<ApiResult<string|null>>};
  expenses:{add(input:ExpenseInput):Promise<ApiResult<ExpenseRecord>>;update(input:ExpenseUpdateInput):Promise<ApiResult<ExpenseRecord>>;delete(id:string):Promise<ApiResult<boolean>>;list(filters?:ExpenseSearchFilters):Promise<ApiResult<ExpenseSummary>>;selectAttachment():Promise<ApiResult<string|null>>;openAttachment(id:string):Promise<ApiResult<boolean>>};
  customers:{list():Promise<ApiResult<CustomerRecord[]>>;create(input:CustomerCreateInput):Promise<ApiResult<CustomerRecord>>;getProfile(id:string):Promise<ApiResult<CustomerProfile>>;findDuplicates(query:CustomerDuplicateQuery):Promise<ApiResult<CustomerDuplicateMatch[]>>;update(input:CustomerUpdateInput):Promise<ApiResult<CustomerRecord>>};
  templates:{list():Promise<ApiResult<ReceiptTemplateRecord[]>>;add(input:ReceiptTemplateInput):Promise<ApiResult<ReceiptTemplateRecord>>;delete(id:string):Promise<ApiResult<boolean>>};
  receipts:{getCoreStatus():Promise<ApiResult<ReceiptCoreStatus>>;issue(input:IssueReceiptInput):Promise<ApiResult<IssueReceiptResult>>;search(filters:ReceiptSearchFilters):Promise<ApiResult<ReceiptSearchResult>>;cancel(receiptId:string,reason:string):Promise<ApiResult<CancelReceiptResult>>;openPdf(receiptId:string,kind?:"original"|"cancellation"):Promise<ApiResult<boolean>>;shareEmail(receiptId:string):Promise<ApiResult<boolean>>;shareWhatsApp(receiptId:string):Promise<ApiResult<boolean>>};
}; } }
export {};
