import React,{useCallback,useEffect,useMemo,useState} from "react";
import {Alert,Pressable,ScrollView,StyleSheet,Text,TextInput,View} from "react-native";
import {SafeAreaView} from "react-native-safe-area-context";
import {theme} from "../theme/theme";
import {StudentLocalStore,type MobileGroup,type MobileLesson,type MobileStudent} from "../students/StudentLocalStore";

type Section="students"|"groups"|"lessons";
const money=(a:number)=>new Intl.NumberFormat("he-IL",{style:"currency",currency:"ILS"}).format(a/100);
const dateTime=(v:string)=>new Intl.DateTimeFormat("he-IL",{dateStyle:"short",timeStyle:"short"}).format(new Date(v));

export default function StudentHubScreen(){
 const[section,setSection]=useState<Section>("students"),[students,setStudents]=useState<MobileStudent[]>([]),[groups,setGroups]=useState<MobileGroup[]>([]),[lessons,setLessons]=useState<MobileLesson[]>([]),[loading,setLoading]=useState(true),[name,setName]=useState(""),[phone,setPhone]=useState(""),[grade,setGrade]=useState(""),[price,setPrice]=useState(""),[groupName,setGroupName]=useState(""),[selected,setSelected]=useState<string[]>([]),[lessonTarget,setLessonTarget]=useState(""),[lessonDate,setLessonDate]=useState(()=>new Date(Date.now()+86400000).toISOString().slice(0,10)),[lessonTime,setLessonTime]=useState("16:00");
 const load=useCallback(async()=>{setLoading(true);try{const[s,g,l]=await Promise.all([StudentLocalStore.listStudents(),StudentLocalStore.listGroups(),StudentLocalStore.listLessons()]);setStudents(s);setGroups(g);setLessons(l)}finally{setLoading(false)}},[]);
 useEffect(()=>{void load()},[load]);
 const studentMap=useMemo(()=>new Map(students.map(x=>[x.id,x])),[students]);
 const groupMap=useMemo(()=>new Map(groups.map(x=>[x.id,x])),[groups]);
 async function addStudent(){try{const amount=Math.round(Number(price.replace(",","."))*100);await StudentLocalStore.saveStudent({displayName:name,phone,schoolGrade:grade,defaultPriceAgorot:Number.isFinite(amount)?amount:0});setName("");setPhone("");setGrade("");setPrice("");await load()}catch(e){Alert.alert("לא ניתן לשמור",e instanceof Error?e.message:"אירעה שגיאה")}}
 async function addGroup(){try{await StudentLocalStore.saveGroup({name:groupName,studentIds:selected});setGroupName("");setSelected([]);await load()}catch(e){Alert.alert("לא ניתן לשמור",e instanceof Error?e.message:"אירעה שגיאה")}}
 async function addLesson(){try{if(!lessonTarget)throw new Error("יש לבחור תלמיד או קבוצה.");const isGroup=lessonTarget.startsWith("group:");const targetId=lessonTarget.slice(lessonTarget.indexOf(":")+1);const dt=new Date(`${lessonDate}T${lessonTime}:00`);const defaultPrice=isGroup?0:(studentMap.get(targetId)?.defaultPriceAgorot??0);await StudentLocalStore.createLesson({kind:isGroup?"group":"individual",studentId:isGroup?null:targetId,groupId:isGroup?targetId:null,title:isGroup?`שיעור קבוצה - ${groupMap.get(targetId)?.name??"קבוצה"}`:`שיעור עם ${studentMap.get(targetId)?.displayName??"תלמיד"}`,startsAt:dt.toISOString(),durationMinutes:60,amountAgorot:defaultPrice});await load()}catch(e){Alert.alert("לא ניתן ליצור שיעור",e instanceof Error?e.message:"אירעה שגיאה")}}
 async function mark(id:string,attendance:"attended"|"absent",payment?:"paid"|"unpaid"){try{await StudentLocalStore.updateLesson(id,{attendance,...(payment?{payment}:{})});await load()}catch(e){Alert.alert("לא ניתן לעדכן",e instanceof Error?e.message:"אירעה שגיאה")}}
 return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.content} keyboardShouldPersistTaps="handled">
  <View style={s.header}><Text style={s.eyebrow}>ניהול תלמידים · מצב בדיקה</Text><Text style={s.title}>התלמידים שלי</Text><Text style={s.subtitle}>הנתונים נשמרים מקומית באפליקציה. קבלות אינן מופקות במצב זה.</Text></View>
  <View style={s.tabs}>{([["students","תלמידים"],["groups","קבוצות"],["lessons","שיעורים"]] as [Section,string][]).map(([key,label])=><Pressable key={key} onPress={()=>setSection(key)} style={[s.tab,section===key&&s.tabActive]}><Text style={[s.tabText,section===key&&s.tabTextActive]}>{label}</Text></Pressable>)}</View>
  {loading?<Text style={s.muted}>טוען…</Text>:section==="students"?<>
   <View style={s.card}><Text style={s.cardTitle}>תלמיד חדש</Text><TextInput style={s.input} value={name} onChangeText={setName} placeholder="שם התלמיד" textAlign="right"/><View style={s.row}><TextInput style={[s.input,s.half]} value={grade} onChangeText={setGrade} placeholder="כיתה" textAlign="right"/><TextInput style={[s.input,s.half]} value={phone} onChangeText={setPhone} placeholder="טלפון" keyboardType="phone-pad" textAlign="right"/></View><TextInput style={s.input} value={price} onChangeText={setPrice} placeholder="מחיר שיעור ₪" keyboardType="decimal-pad" textAlign="right"/><Pressable style={s.primary} onPress={()=>void addStudent()}><Text style={s.primaryText}>הוסף תלמיד</Text></Pressable></View>
   {students.map(x=><View key={x.id} style={s.item}><View><Text style={s.itemTitle}>{x.displayName}</Text><Text style={s.muted}>{[x.schoolGrade&&`כיתה ${x.schoolGrade}`,x.phone].filter(Boolean).join(" · ")||"ללא פרטים נוספים"}</Text></View><Text style={s.amount}>{money(x.defaultPriceAgorot)}</Text></View>)}
  </>:section==="groups"?<>
   <View style={s.card}><Text style={s.cardTitle}>קבוצה חדשה</Text><TextInput style={s.input} value={groupName} onChangeText={setGroupName} placeholder="שם הקבוצה" textAlign="right"/><Text style={s.label}>בחרי לפחות שני תלמידים</Text><View style={s.chips}>{students.map(st=><Pressable key={st.id} onPress={()=>setSelected(v=>v.includes(st.id)?v.filter(x=>x!==st.id):[...v,st.id])} style={[s.chip,selected.includes(st.id)&&s.chipActive]}><Text style={selected.includes(st.id)?s.chipTextActive:s.chipText}>{st.displayName}</Text></Pressable>)}</View><Pressable style={s.primary} onPress={()=>void addGroup()}><Text style={s.primaryText}>צור קבוצה</Text></Pressable></View>
   {groups.map(g=><View key={g.id} style={s.item}><View><Text style={s.itemTitle}>{g.name}</Text><Text style={s.muted}>{g.studentIds.map(id=>studentMap.get(id)?.displayName).filter(Boolean).join(", ")}</Text></View><Text style={s.badge}>{g.studentIds.length}</Text></View>)}
  </>:<>
   <View style={s.card}><Text style={s.cardTitle}>שיעור חדש</Text><Text style={s.label}>בחרי תלמיד או קבוצה</Text><View style={s.chips}>{students.map(st=><Pressable key={st.id} onPress={()=>setLessonTarget(`student:${st.id}`)} style={[s.chip,lessonTarget===`student:${st.id}`&&s.chipActive]}><Text style={lessonTarget===`student:${st.id}`?s.chipTextActive:s.chipText}>{st.displayName}</Text></Pressable>)}{groups.map(g=><Pressable key={g.id} onPress={()=>setLessonTarget(`group:${g.id}`)} style={[s.chip,lessonTarget===`group:${g.id}`&&s.chipActive]}><Text style={lessonTarget===`group:${g.id}`?s.chipTextActive:s.chipText}>👥 {g.name}</Text></Pressable>)}</View><View style={s.row}><TextInput style={[s.input,s.half]} value={lessonDate} onChangeText={setLessonDate} placeholder="YYYY-MM-DD" textAlign="center"/><TextInput style={[s.input,s.half]} value={lessonTime} onChangeText={setLessonTime} placeholder="HH:MM" textAlign="center"/></View><Pressable style={s.primary} onPress={()=>void addLesson()}><Text style={s.primaryText}>הוסף ליומן</Text></Pressable></View>
   {lessons.map(l=>{const target=l.kind==="group"?groupMap.get(l.groupId??"")?.name:studentMap.get(l.studentId??"")?.displayName;return <View key={l.id} style={s.lesson}><View style={s.lessonTop}><View><Text style={s.itemTitle}>{target??l.title}</Text><Text style={s.muted}>{dateTime(l.startsAt)} · {l.kind==="group"?"קבוצתי":"פרטני"}</Text></View><Text style={l.payment==="paid"?s.paid:s.unpaid}>{l.payment==="paid"?"שולם":"לא שולם"}</Text></View><View style={s.lessonActions}><Pressable style={s.action} onPress={()=>void mark(l.id,"attended")}><Text>הגיע</Text></Pressable><Pressable style={s.action} onPress={()=>void mark(l.id,"absent")}><Text>לא הגיע</Text></Pressable><Pressable style={[s.action,s.pay]} onPress={()=>void mark(l.id,"attended","paid")}><Text style={s.payText}>שולם</Text></Pressable></View></View>})}
  </>}
 </ScrollView></SafeAreaView>;
}

const s=StyleSheet.create({safe:{flex:1,backgroundColor:theme.background},content:{padding:16,paddingBottom:110,gap:12},header:{gap:5,marginBottom:4},eyebrow:{textAlign:"right",fontSize:12,fontWeight:"700",color:theme.primary},title:{textAlign:"right",fontSize:28,fontWeight:"800",color:theme.text},subtitle:{textAlign:"right",fontSize:13,lineHeight:20,color:theme.muted},tabs:{flexDirection:"row-reverse",gap:8},tab:{flex:1,paddingVertical:10,borderRadius:12,borderWidth:1,borderColor:theme.border,backgroundColor:theme.surface},tabActive:{backgroundColor:theme.primary,borderColor:theme.primary},tabText:{textAlign:"center",fontWeight:"700",color:theme.text},tabTextActive:{color:"white"},card:{backgroundColor:theme.surface,borderRadius:theme.radius,padding:14,gap:10,borderWidth:1,borderColor:theme.border},cardTitle:{textAlign:"right",fontWeight:"800",fontSize:17,color:theme.text},input:{borderWidth:1,borderColor:theme.border,borderRadius:12,backgroundColor:"white",paddingHorizontal:12,paddingVertical:10,color:theme.text},row:{flexDirection:"row-reverse",gap:8},half:{flex:1},primary:{backgroundColor:theme.primary,borderRadius:12,paddingVertical:12},primaryText:{color:"white",fontWeight:"800",textAlign:"center"},item:{backgroundColor:theme.surface,borderRadius:14,borderWidth:1,borderColor:theme.border,padding:13,flexDirection:"row-reverse",justifyContent:"space-between",alignItems:"center",gap:12},itemTitle:{fontWeight:"800",fontSize:15,color:theme.text,textAlign:"right"},muted:{color:theme.muted,fontSize:12,textAlign:"right"},amount:{fontWeight:"800",color:theme.primary},badge:{minWidth:30,textAlign:"center",backgroundColor:theme.primarySoft,color:theme.primary,paddingVertical:5,paddingHorizontal:8,borderRadius:999,fontWeight:"800"},label:{textAlign:"right",fontSize:12,fontWeight:"700",color:theme.muted},chips:{flexDirection:"row-reverse",flexWrap:"wrap",gap:7},chip:{borderWidth:1,borderColor:theme.border,borderRadius:999,paddingVertical:7,paddingHorizontal:10,backgroundColor:"white"},chipActive:{backgroundColor:theme.primary,borderColor:theme.primary},chipText:{color:theme.text,fontWeight:"600"},chipTextActive:{color:"white",fontWeight:"700"},lesson:{backgroundColor:theme.surface,borderRadius:14,borderWidth:1,borderColor:theme.border,padding:13,gap:10},lessonTop:{flexDirection:"row-reverse",justifyContent:"space-between",alignItems:"flex-start",gap:10},paid:{color:"#166534",fontWeight:"800"},unpaid:{color:"#92400e",fontWeight:"800"},lessonActions:{flexDirection:"row-reverse",gap:7},action:{flex:1,borderWidth:1,borderColor:theme.border,borderRadius:10,paddingVertical:9,alignItems:"center",backgroundColor:"white"},pay:{backgroundColor:theme.primary,borderColor:theme.primary},payText:{color:"white",fontWeight:"800"}});
