import React,{useCallback,useEffect,useState} from "react";
import {Alert,Pressable,RefreshControl,ScrollView,StyleSheet,Text,TextInput,View} from "react-native";
import {SafeAreaView} from "react-native-safe-area-context";
import {useBusiness} from "../context/BusinessContext";
import {archiveCloudStudent,listCloudStudents,saveCloudStudent,type CloudStudent} from "../data/supabase/StudentCloudRepository";
import {CloudGroupsPanel} from "../students/CloudGroupsPanel";
import {CloudSchedulePanel} from "../students/CloudSchedulePanel";
import {theme} from "../theme/theme";

const money=(a:number)=>new Intl.NumberFormat("he-IL",{style:"currency",currency:"ILS"}).format(a/100);
const fromPrice=(v:string)=>{const n=Number(v.replace(",","."));return Number.isFinite(n)&&n>=0?Math.round(n*100):0};

export default function StudentCloudScreen(){
 const {businessId,loading}=useBusiness();
 const [students,setStudents]=useState<CloudStudent[]>([]),[busy,setBusy]=useState(false),[editing,setEditing]=useState<CloudStudent|null>(null);
 const [section,setSection]=useState<"students"|"groups"|"schedule"|"payments">("students");
 const [name,setName]=useState(""),[phone,setPhone]=useState(""),[grade,setGrade]=useState(""),[price,setPrice]=useState(""),[notes,setNotes]=useState(""),[guardianName,setGuardianName]=useState(""),[guardianPhone,setGuardianPhone]=useState(""),[guardianReminder,setGuardianReminder]=useState(false),[reminderEnabled,setReminderEnabled]=useState(false);
 const reset=()=>{setEditing(null);setName("");setPhone("");setGrade("");setPrice("");setNotes("");setGuardianName("");setGuardianPhone("");setGuardianReminder(false);setReminderEnabled(false)};
 const load=useCallback(async()=>{if(!businessId)return;setBusy(true);try{setStudents(await listCloudStudents(businessId))}catch(e){Alert.alert("טעינת תלמידים נכשלה",e instanceof Error?e.message:"נסי שוב")}finally{setBusy(false)}},[businessId]);
 useEffect(()=>{void load()},[load]);
 const edit=(student:CloudStudent)=>{setEditing(student);setName(student.displayName);setPhone(student.phone??"");setGrade(student.schoolGrade??"");setPrice(String(student.defaultPriceAgorot/100));setNotes(student.focusNotes??"");setGuardianName(student.primaryGuardian?.displayName??"");setGuardianPhone(student.primaryGuardian?.phone??"");setGuardianReminder(Boolean(student.primaryGuardian?.receivesReminders));setReminderEnabled(student.reminderEnabled)};
 const save=async()=>{if(!businessId)return;setBusy(true);try{await saveCloudStudent(businessId,{id:editing?.id,displayName:name,phone,schoolGrade:grade,focusNotes:notes,defaultPriceAgorot:fromPrice(price),reminderEnabled,guardianName,guardianPhone,guardianReceivesReminders:guardianReminder});reset();await load()}catch(e){Alert.alert("שמירת תלמיד נכשלה",e instanceof Error?e.message:"נסי שוב")}finally{setBusy(false)}};
 const archive=(student:CloudStudent)=>Alert.alert("הסתרת תלמיד",`להסתיר את ${student.displayName} מרשימת התלמידים הפעילים?`,[{text:"ביטול",style:"cancel"},{text:"הסתר",style:"destructive",onPress:()=>void (async()=>{if(!businessId)return;setBusy(true);try{await archiveCloudStudent(businessId,student.id);await load()}catch(e){Alert.alert("לא ניתן להסתיר",e instanceof Error?e.message:"נסי שוב")}finally{setBusy(false)}})()}]);
 if(loading)return <SafeAreaView style={s.safe}><Text style={s.loading}>מתחבר לענן…</Text></SafeAreaView>;
 if(!businessId)return <SafeAreaView style={s.safe}><Text style={s.loading}>יש להתחבר לחשבון העסק כדי לנהל תלמידים.</Text></SafeAreaView>;
 return <SafeAreaView style={s.safe}>{section==="schedule"?<CloudSchedulePanel businessId={businessId} students={students}/>:section==="payments"?<CloudSchedulePanel businessId={businessId} students={students} paymentsOnly/>:section==="groups"?<CloudGroupsPanel businessId={businessId} students={students}/>:<ScrollView contentContainerStyle={s.content} refreshControl={<RefreshControl refreshing={busy} onRefresh={()=>void load()}/>} keyboardShouldPersistTaps="handled">
  <Text style={s.eyebrow}>ניהול תלמידים בענן</Text><Text style={s.title}>התלמידים שלי</Text><Text style={s.subtitle}>הנתונים נשמרים בענן המשותף ומופיעים גם ב־Windows.</Text>
  <View style={s.card}><Text style={s.cardTitle}>{editing?"עריכת תלמיד":"תלמיד חדש"}</Text><TextInput style={s.input} value={name} onChangeText={setName} placeholder="שם התלמיד" maxLength={160} textAlign="right"/><View style={s.row}><TextInput style={[s.input,s.half]} value={grade} onChangeText={setGrade} placeholder="כיתה" maxLength={80} textAlign="right"/><TextInput style={[s.input,s.half]} value={phone} onChangeText={setPhone} placeholder="טלפון" maxLength={20} keyboardType="phone-pad" textAlign="right"/></View><TextInput style={s.input} value={price} onChangeText={setPrice} placeholder="מחיר שיעור ₪" keyboardType="decimal-pad" textAlign="right"/><TextInput style={[s.input,s.notes]} value={notes} onChangeText={setNotes} placeholder="דגשים / מטרות / מידע חשוב" maxLength={4000} multiline textAlignVertical="top" textAlign="right"/><Text style={s.label}>הורה ראשי ותזכורות</Text><TextInput style={s.input} value={guardianName} onChangeText={setGuardianName} placeholder="שם ההורה" maxLength={160} textAlign="right"/><TextInput style={s.input} value={guardianPhone} onChangeText={setGuardianPhone} placeholder="טלפון הורה" maxLength={20} keyboardType="phone-pad" textAlign="right"/><View style={s.row}><Pressable style={[s.toggle,reminderEnabled&&s.toggleActive]} onPress={()=>setReminderEnabled(v=>!v)}><Text style={reminderEnabled?s.toggleActiveText:s.toggleText}>תזכורות לתלמיד</Text></Pressable><Pressable style={[s.toggle,guardianReminder&&s.toggleActive]} onPress={()=>setGuardianReminder(v=>!v)}><Text style={guardianReminder?s.toggleActiveText:s.toggleText}>אישור הורה לתזכורות</Text></Pressable></View><View style={s.row}><Pressable style={[s.primary,s.half]} onPress={()=>void save()} disabled={busy}><Text style={s.primaryText}>{editing?"שמירת שינויים":"הוספת תלמיד"}</Text></Pressable>{editing?<Pressable style={[s.secondary,s.half]} onPress={reset}><Text style={s.secondaryText}>ביטול</Text></Pressable>:null}</View></View>
  {students.map(student=><View key={student.id} style={s.item}><View style={{flex:1}}><Text style={s.itemTitle}>{student.displayName}</Text><Text style={s.meta}>{[student.schoolGrade&&`כיתה ${student.schoolGrade}`,student.phone].filter(Boolean).join(" · ")||"ללא פרטים נוספים"}</Text>{student.primaryGuardian?<Text style={s.guardianMeta}>הורה ראשי: {student.primaryGuardian.displayName}{student.primaryGuardian.receivesReminders?" · מאשר תזכורות":""}</Text>:null}{student.focusNotes?<Text style={s.notesText}>{student.focusNotes}</Text>:null}</View><View style={s.actions}><Text style={s.amount}>{money(student.defaultPriceAgorot)}</Text><Pressable onPress={()=>edit(student)}><Text style={s.edit}>עריכה</Text></Pressable><Pressable onPress={()=>archive(student)}><Text style={s.archive}>הסתרה</Text></Pressable></View></View>)}
  {!busy&&!students.length?<View style={s.empty}><Text style={s.meta}>עדיין אין תלמידים בענן.</Text></View>:null}
 </ScrollView>}<View style={s.switcher}><Pressable onPress={()=>setSection("students")} style={[s.switchButton,section==="students"&&s.switchActive]}><Text style={section==="students"?s.switchActiveText:s.switchText}>תלמידים</Text></Pressable><Pressable onPress={()=>setSection("groups")} style={[s.switchButton,section==="groups"&&s.switchActive]}><Text style={section==="groups"?s.switchActiveText:s.switchText}>קבוצות</Text></Pressable><Pressable onPress={()=>setSection("schedule")} style={[s.switchButton,section==="schedule"&&s.switchActive]}><Text style={section==="schedule"?s.switchActiveText:s.switchText}>יומן</Text></Pressable><Pressable onPress={()=>setSection("payments")} style={[s.switchButton,section==="payments"&&s.switchActive]}><Text style={section==="payments"?s.switchActiveText:s.switchText}>גבייה</Text></Pressable></View></SafeAreaView>;
}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:theme.background},content:{padding:18,paddingBottom:170,gap:12},loading:{margin:24,textAlign:"center",color:theme.muted},eyebrow:{textAlign:"right",fontWeight:"900",color:theme.accentStrong},title:{textAlign:"right",fontSize:30,fontWeight:"900",color:theme.text},subtitle:{textAlign:"right",fontSize:13,color:theme.muted,lineHeight:20},card:{backgroundColor:theme.surface,borderRadius:theme.radius,padding:17,gap:10,borderWidth:1,borderColor:theme.border},cardTitle:{textAlign:"right",fontSize:18,fontWeight:"900",color:theme.text},label:{textAlign:"right",fontWeight:"800",color:theme.text},input:{borderWidth:1,borderColor:theme.border,borderRadius:15,backgroundColor:"#FBFCFF",padding:12,color:theme.text},notes:{minHeight:75},row:{flexDirection:"row-reverse",gap:8},half:{flex:1},toggle:{flex:1,borderWidth:1,borderColor:theme.border,borderRadius:13,padding:11,alignItems:"center"},toggleActive:{backgroundColor:theme.primary,borderColor:theme.primary},toggleText:{color:theme.text,fontWeight:"700",fontSize:12},toggleActiveText:{color:"#fff",fontWeight:"800",fontSize:12},primary:{backgroundColor:theme.accent,borderRadius:15,padding:14},primaryText:{color:theme.navy,fontWeight:"900",textAlign:"center"},secondary:{borderColor:theme.border,borderWidth:1,borderRadius:15,padding:14},secondaryText:{color:theme.text,fontWeight:"700",textAlign:"center"},item:{backgroundColor:theme.surface,borderWidth:1,borderColor:theme.border,borderRadius:18,padding:15,flexDirection:"row-reverse",gap:12},itemTitle:{textAlign:"right",fontWeight:"900",fontSize:16,color:theme.text},meta:{textAlign:"right",fontSize:12,color:theme.muted,marginTop:3},guardianMeta:{textAlign:"right",fontSize:12,color:theme.accentStrong,marginTop:5,fontWeight:"700"},notesText:{textAlign:"right",fontSize:12,color:theme.text,marginTop:5},actions:{alignItems:"flex-end",gap:7},amount:{fontWeight:"900",color:theme.primary},edit:{color:theme.accentStrong,fontWeight:"800",fontSize:12},archive:{color:theme.danger,fontWeight:"800",fontSize:12},empty:{padding:22,alignItems:"center"},switcher:{position:"absolute",bottom:15,left:18,right:18,flexDirection:"row-reverse",gap:8,padding:7,backgroundColor:theme.navy,borderRadius:18},switchButton:{flex:1,padding:12,alignItems:"center",borderRadius:13},switchActive:{backgroundColor:theme.accent},switchText:{color:"#E2EBF8",fontWeight:"800"},switchActiveText:{color:theme.navy,fontWeight:"900"}});
