import { contextBridge, ipcRenderer } from "electron";
import type { BusinessSettingsInput, BusinessSettingsRecord, DatabaseHealthReport, IssueReceiptInput, IssueReceiptResult, OnboardingStatus, ReceiptCoreStatus, ReceiptSearchFilters, ReceiptSearchResult, CustomerRecord, CustomerProfile, CustomerCreateInput, CustomerUpdateInput, CustomerDuplicateQuery, CustomerDuplicateMatch, CancelReceiptResult, ReportFilters, DateRangeReport, AnnualReport, BackupOverview, BackupRecord, BackupInspection, RestoreResult, CloudSyncStatus, CloudSyncConnectInput, SupabaseCloudStatus, SupabaseCloudDevice, SupabaseCloudConnectInput, SupabaseCloudPasswordChangeInput, SupabaseCloudPasswordRecoveryRequestInput, SupabaseCloudPasswordRecoveryConfirmInput, FullHealthReport, ErrorLogRecord, SecurityStatus, DiagnosticPreview, DiagnosticPackageResult, QaReport, QaExportResult, OpenFormatExportResult, SimulatorSubmissionPackageResult, TaxRegistrationDossierInput, TaxRegistrationDossierResult, ExpenseInput, ExpenseUpdateInput, ExpenseSearchFilters, ExpenseRecord, ExpenseSummary, ReceiptTemplateInput, ReceiptTemplateRecord, SimulatorOfficialResultInput, SimulatorOfficialResultImport } from "../../../../packages/database/src/types";
import type { StudentSaveInput, StudentWithGuardian, LessonSeriesRecord, LessonSeriesSaveInput, LessonCalendarItem, LessonParticipantRecord, AttendanceStatus, LessonPaymentStatus } from "../../../../packages/database/src/studentTypes";
import type { ApiResult } from "../../../../packages/shared/src/api";
import type { LessonReminderHistoryItem } from "../../../../packages/database/src/reminderHistoryTypes";
import type { StudentGroupWithMembers, StudentGroupSaveInput, GroupLessonSeriesSaveInput } from "../../../../packages/database/src/groupTypes";
export interface AppInfo { productName:string; foundationVersion:string; platform:NodeJS.Platform; apiVersion:string; }
export interface AboutInfo {productName:string;version:string;buildNumber:string;channel:string;builtAt:string;databaseVersion:number;pdfTemplateVersion:number;appId:string;businessId:string;dataFolder:string;backupFolder:string|null;receiptsFolder:string;healthStatus:"healthy"|"warning"|"critical";}
export interface LessonParticipantUpdateResult {participant:LessonParticipantRecord;receipt:null|{id:string;receiptNumber:number;pdfCreated:boolean;pdfPath:string|null;warningCode:string|null};}
export interface ReminderDispatchStatus {providerId:string;configured:boolean;running:boolean;}
export interface ReminderDispatchSummary {providerId:string;configured:boolean;claimed:number;sent:number;failed:number;skipped:number;}
export interface GoogleCalendarStatus {configured:boolean;clientSecretConfigured:boolean;connected:boolean;syncing:boolean;calendarId:string;lastSyncAt:string|null;lastError:string|null;}
export interface GoogleCalendarSyncResult {total:number;created:number;updated:number;deleted:number;failed:number;}
const appInfo:AppInfo=Object.freeze({productName:"מפתחות להצלחה",foundationVersion:"1.1.0",platform:process.platform,apiVersion:"1.0"});
const invoke=<T>(channel:string,payload?:unknown):Promise<ApiResult<T>>=>ipcRenderer.invoke(channel,payload);
contextBridge.exposeInMainWorld("mkApi",Object.freeze({
 app:Object.freeze({getInfo:():AppInfo=>appInfo,getAbout:():Promise<ApiResult<AboutInfo>>=>invoke("app:get-about"),openFolder:(kind:"data"|"backups"|"receipts"):Promise<ApiResult<boolean>>=>invoke("app:open-folder",{kind}),copyTechnicalInfo:():Promise<ApiResult<boolean>>=>invoke("app:copy-technical-info"),getDiagnosticPreview:():Promise<ApiResult<DiagnosticPreview>>=>invoke("app:get-diagnostic-preview"),createDiagnosticPackage:():Promise<ApiResult<DiagnosticPackageResult|null>>=>invoke("app:create-diagnostic-package"),openDiagnosticsFolder:():Promise<ApiResult<boolean>>=>invoke("app:open-diagnostics-folder")}),
 database:Object.freeze({getHealth:():Promise<ApiResult<DatabaseHealthReport>>=>invoke("database:get-health"),getBusinessSettings:():Promise<ApiResult<BusinessSettingsRecord|null>>=>invoke("database:get-business-settings")}),
 taxOpen:Object.freeze({createRegistrationFixture:():Promise<ApiResult<string>>=>invoke("tax-open:create-registration-fixture"),export:(fromDate:string,toDate:string):Promise<ApiResult<OpenFormatExportResult|null>>=>invoke("tax-open:export",{fromDate,toDate}),createSimulatorPackage:(folderPath:string):Promise<ApiResult<SimulatorSubmissionPackageResult>>=>invoke("tax-open:create-simulator-package",{folderPath}),saveSimulatorSummaryPdf:(submissionFolder:string,input:SimulatorOfficialResultInput):Promise<ApiResult<string|null>>=>invoke("tax-open:save-simulator-summary-pdf",{submissionFolder,...input}),importSimulatorResult:(submissionFolder:string,input:SimulatorOfficialResultInput):Promise<ApiResult<SimulatorOfficialResultImport|null>>=>invoke("tax-open:import-simulator-result",{submissionFolder,...input}),createRegistrationDossier:(submissionFolder:string,input:TaxRegistrationDossierInput):Promise<ApiResult<TaxRegistrationDossierResult>>=>invoke("tax-open:create-registration-dossier",{submissionFolder,...input}),openFolder:(folderPath:string):Promise<ApiResult<boolean>>=>invoke("tax-open:open-folder",{folderPath})}),
 qa:Object.freeze({run:():Promise<ApiResult<QaReport>>=>invoke("qa:run"),exportReport:():Promise<ApiResult<QaExportResult|null>>=>invoke("qa:export")}),health:Object.freeze({runFull:():Promise<ApiResult<FullHealthReport>>=>invoke("health:run-full"),getSecurityStatus:():Promise<ApiResult<SecurityStatus>>=>invoke("health:get-security-status")}),errors:Object.freeze({list:():Promise<ApiResult<ErrorLogRecord[]>>=>invoke("errors:list")}),
 settings:Object.freeze({getOnboardingStatus:():Promise<ApiResult<OnboardingStatus>>=>invoke("settings:get-onboarding-status"),completeSetup:(input:BusinessSettingsInput):Promise<ApiResult<BusinessSettingsRecord>>=>invoke("settings:complete-setup",input),verifyPin:(pin:string):Promise<ApiResult<boolean>>=>invoke("settings:verify-pin",{pin})}),dialogs:Object.freeze({selectImage:():Promise<ApiResult<string|null>>=>invoke("dialogs:select-image"),selectFolder:():Promise<ApiResult<string|null>>=>invoke("dialogs:select-folder")}),
 cloudAccount:Object.freeze({getStatus:():Promise<ApiResult<SupabaseCloudStatus>>=>invoke("cloud-account:get-status"),connect:(input:SupabaseCloudConnectInput):Promise<ApiResult<SupabaseCloudStatus>>=>invoke("cloud-account:connect",input),changePassword:(input:SupabaseCloudPasswordChangeInput):Promise<ApiResult<void>>=>invoke("cloud-account:change-password",input),requestPasswordRecovery:(input:SupabaseCloudPasswordRecoveryRequestInput):Promise<ApiResult<void>>=>invoke("cloud-account:request-password-recovery",input),recoverPassword:(input:SupabaseCloudPasswordRecoveryConfirmInput):Promise<ApiResult<void>>=>invoke("cloud-account:recover-password",input),disconnect:():Promise<ApiResult<SupabaseCloudStatus>>=>invoke("cloud-account:disconnect"),refresh:():Promise<ApiResult<SupabaseCloudStatus>>=>invoke("cloud-account:refresh"),listDevices:():Promise<ApiResult<SupabaseCloudDevice[]>>=>invoke("cloud-account:list-devices"),revokeDevice:(deviceId:string):Promise<ApiResult<void>>=>invoke("cloud-account:revoke-device",{deviceId})}),
 cloudSync:Object.freeze({getStatus:():Promise<ApiResult<CloudSyncStatus>>=>invoke("cloud-sync:get-status"),connect:(input:CloudSyncConnectInput):Promise<ApiResult<CloudSyncStatus>>=>invoke("cloud-sync:connect",input),disconnect:():Promise<ApiResult<CloudSyncStatus>>=>invoke("cloud-sync:disconnect"),syncNow:():Promise<ApiResult<CloudSyncStatus>>=>invoke("cloud-sync:sync-now"),pull:():Promise<ApiResult<CloudSyncStatus>>=>invoke("cloud-sync:pull"),forcePush:():Promise<ApiResult<CloudSyncStatus>>=>invoke("cloud-sync:force-push")}),
 backups:Object.freeze({getOverview:():Promise<ApiResult<BackupOverview>>=>invoke("backups:get-overview"),create:():Promise<ApiResult<BackupRecord|null>>=>invoke("backups:create"),createGoogleDrive:():Promise<ApiResult<BackupRecord>>=>invoke("backups:create-google-drive"),createTransfer:():Promise<ApiResult<BackupRecord|null>>=>invoke("backups:create-transfer"),inspect:():Promise<ApiResult<BackupInspection|null>>=>invoke("backups:inspect"),restore:():Promise<ApiResult<RestoreResult|null>>=>invoke("backups:restore"),openFolder:():Promise<ApiResult<boolean>>=>invoke("backups:open-folder")}),
 reports:Object.freeze({getRange:(filters:ReportFilters):Promise<ApiResult<DateRangeReport>>=>invoke("reports:get-range",filters),getAnnual:(year:number):Promise<ApiResult<AnnualReport>>=>invoke("reports:get-annual",{year}),exportCsv:(filters:ReportFilters):Promise<ApiResult<string|null>>=>invoke("reports:export-csv",filters),exportAccountantPackage:(year:number):Promise<ApiResult<string|null>>=>invoke("reports:export-accountant",{year})}),expenses:Object.freeze({add:(input:ExpenseInput):Promise<ApiResult<ExpenseRecord>>=>invoke("expenses:add",input),update:(input:ExpenseUpdateInput):Promise<ApiResult<ExpenseRecord>>=>invoke("expenses:update",input),delete:(id:string):Promise<ApiResult<boolean>>=>invoke("expenses:delete",{id}),list:(filters:ExpenseSearchFilters={}):Promise<ApiResult<ExpenseSummary>>=>invoke("expenses:list",filters),selectAttachment:():Promise<ApiResult<string|null>>=>invoke("expenses:select-attachment"),openAttachment:(id:string):Promise<ApiResult<boolean>>=>invoke("expenses:open-attachment",{id})}),
 customers:Object.freeze({list:():Promise<ApiResult<CustomerRecord[]>>=>invoke("customers:list"),create:(input:CustomerCreateInput):Promise<ApiResult<CustomerRecord>>=>invoke("customers:create",input),getProfile:(id:string):Promise<ApiResult<CustomerProfile>>=>invoke("customers:get-profile",{id}),findDuplicates:(query:CustomerDuplicateQuery):Promise<ApiResult<CustomerDuplicateMatch[]>>=>invoke("customers:find-duplicates",query),update:(input:CustomerUpdateInput):Promise<ApiResult<CustomerRecord>>=>invoke("customers:update",input)}),
 students:Object.freeze({list:():Promise<ApiResult<StudentWithGuardian[]>>=>invoke("students:list"),save:(input:StudentSaveInput):Promise<ApiResult<StudentWithGuardian>>=>invoke("students:save",input),deactivate:(studentId:string):Promise<ApiResult<void>>=>invoke("students:deactivate",{studentId})}),
 groups:Object.freeze({list:():Promise<ApiResult<StudentGroupWithMembers[]>>=>invoke("groups:list"),save:(input:StudentGroupSaveInput):Promise<ApiResult<StudentGroupWithMembers>>=>invoke("groups:save",input),deactivate:(groupId:string):Promise<ApiResult<void>>=>invoke("groups:deactivate",{groupId}),createSeries:(input:GroupLessonSeriesSaveInput):Promise<ApiResult<unknown>>=>invoke("groups:create-series",input),listCalendar:(fromIso:string,toIso:string):Promise<ApiResult<LessonCalendarItem[]>>=>invoke("groups:list-calendar",{fromIso,toIso})}),
 lessons:Object.freeze({listSeries:():Promise<ApiResult<LessonSeriesRecord[]>>=>invoke("lessons:list-series"),createSeries:(input:LessonSeriesSaveInput):Promise<ApiResult<LessonSeriesRecord>>=>invoke("lessons:create-series",input),listCalendar:(fromIso:string,toIso:string):Promise<ApiResult<LessonCalendarItem[]>>=>invoke("lessons:list-calendar",{fromIso,toIso}),saveNotes:(lessonId:string,lessonSummary:string,homework:string):Promise<ApiResult<import("../../../../packages/database/src/studentTypes").LessonRecord>>=>invoke("lessons:save-notes",{lessonId,lessonSummary,homework}),updateParticipant:(participantId:string,attendanceStatus:AttendanceStatus,paymentStatus:LessonPaymentStatus,paymentMethod:string|null,amountAgorot:number):Promise<ApiResult<LessonParticipantUpdateResult>>=>invoke("lessons:update-participant",{participantId,attendanceStatus,paymentStatus,paymentMethod,amountAgorot})}),
 reminders:Object.freeze({getStatus:():Promise<ApiResult<ReminderDispatchStatus>>=>invoke("reminders:get-status"),dispatchNow:(limit=20):Promise<ApiResult<ReminderDispatchSummary>>=>invoke("reminders:dispatch-now",{limit}),listRecent:(limit=50):Promise<ApiResult<LessonReminderHistoryItem[]>>=>invoke("reminders:list-recent",{limit}),retryFailed:(reminderId:string):Promise<ApiResult<void>>=>invoke("reminders:retry-failed",{reminderId}),copyManualWhatsApp:(message:string):Promise<ApiResult<void>>=>invoke("reminders:copy-manual-whatsapp",{message}),openManualWhatsApp:(phone:string,message:string):Promise<ApiResult<void>>=>invoke("reminders:open-manual-whatsapp",{phone,message})}),
 googleCalendar:Object.freeze({getStatus:():Promise<ApiResult<GoogleCalendarStatus>>=>invoke("google-calendar:get-status"),setClientId:(clientId:string):Promise<ApiResult<GoogleCalendarStatus>>=>invoke("google-calendar:set-client-id",{clientId}),setClientSecret:(clientSecret:string):Promise<ApiResult<GoogleCalendarStatus>>=>invoke("google-calendar:set-client-secret",{clientSecret}),connect:():Promise<ApiResult<GoogleCalendarStatus>>=>invoke("google-calendar:connect"),disconnect:():Promise<ApiResult<GoogleCalendarStatus>>=>invoke("google-calendar:disconnect"),syncNow:():Promise<ApiResult<GoogleCalendarSyncResult>>=>invoke("google-calendar:sync-now")}),
 templates:Object.freeze({list:():Promise<ApiResult<ReceiptTemplateRecord[]>>=>invoke("templates:list"),add:(input:ReceiptTemplateInput):Promise<ApiResult<ReceiptTemplateRecord>>=>invoke("templates:add",input),delete:(id:string):Promise<ApiResult<boolean>>=>invoke("templates:delete",{id})}),receipts:Object.freeze({getCoreStatus:():Promise<ApiResult<ReceiptCoreStatus>>=>invoke("receipts:get-core-status"),issue:(input:IssueReceiptInput):Promise<ApiResult<IssueReceiptResult>>=>invoke("receipts:issue",input),search:(filters:ReceiptSearchFilters):Promise<ApiResult<ReceiptSearchResult>>=>invoke("receipts:search",filters),cancel:(receiptId:string,reason:string):Promise<ApiResult<CancelReceiptResult>>=>invoke("receipts:cancel",{receiptId,reason}),openPdf:(receiptId:string,kind:"original"|"cancellation"="original"):Promise<ApiResult<boolean>>=>invoke("receipts:open-pdf",{receiptId,kind}),shareEmail:(receiptId:string):Promise<ApiResult<boolean>>=>invoke("receipts:share-email",{receiptId}),shareWhatsApp:(receiptId:string):Promise<ApiResult<boolean>>=>invoke("receipts:share-whatsapp",{receiptId})})
}));
