import React,{useCallback,useEffect,useMemo,useState} from "react";
import {Alert,Pressable,RefreshControl,ScrollView,StyleSheet,Text,TextInput,View} from "react-native";
import type {CloudStudent} from "../data/supabase/StudentCloudRepository";
import {listCloudStudentGroups,type CloudStudentGroup} from "../data/supabase/GroupCloudRepository";
import {createCloudGroupLessonSeries,createCloudLessonSeries,listCloudLessonCalendar,saveCloudLessonNotes,updateCloudLessonParticipant,type CloudLessonItem} from "../data/supabase/LessonCloudRepository";
import {theme} from "../theme/theme";

const today=()=>new Date().toISOString().slice(0,10);
const dateTime=(iso:string)=>new Intl.DateTimeFormat("he-IL",{weekday:"short",day:"numeric",month:"numeric",hour:"2-digit",minute:"2-digit"}).format(new Date(iso));
const money=(agorot:number)=>new Intl.NumberFormat("he-IL",{style:"currency",currency:"ILS",minimumFractionDigits:0}).format(agorot/100);
const reminderOptions=[0,60,180,1440] as const;
const reminderLabel=(minutes:number)=>minutes===0?"ללא תזכורת":minutes===60?"שעה לפני":minutes===180?"3 שעות לפני":"יום לפני";

export function CloudSchedulePanel({businessId,students}:{businessId:string;students:CloudStudent[]}){
 const [items,setItems]=useState<CloudLessonItem[]>([]),[groups,setGroups]=useState<CloudStudentGroup[]>([]),[busy,setBusy]=useState(false),[studentId,setStudentId]=useState<string|null>(null),[groupId,setGroupId]=useState<string|null>(null),[lessonType,setLessonType]=useState<"individual"|"group">("individual");
 const [date,setDate]=useState(today()),[time,setTime]=useState("16:30"),[title,setTitle]=useState("שיעור אישי"),[price,setPrice]=useState(""),[interval,setInterval]=useState<1|2>(1),[endDate,setEndDate]=useState(""),[parentReminderMinutes,setParentReminderMinutes]=useState<number>(1440),[studentReminderMinutes,setStudentReminderMinutes]=useState<number>(1440);
 const [notesTarget,setNotesTarget]=useState<CloudLessonItem|null>(null),[summary,setSummary]=useState(""),[homework,setHomework]=useState("");
 const range=useMemo(()=>{const from=new Date();from.setHours(0,0,0,0);const to=new Date(from);to.setDate(to.getDate()+28);return{from:from.toISOString(),to:to.toISOString()};},[]);
 const load=useCallback(async()=>{setBusy(true);try{const [calendar,cloudGroups]=await Promise.all([listCloudLessonCalendar(businessId,range.from,range.to),listCloudStudentGroups(businessId)]);setItems(calendar);setGroups(cloudGroups)}catch(e){Alert.alert("טעינת היומן נכשלה",e instanceof Error?e.message:"נסי שוב") }finally{setBusy(false)}},[businessId,range.from,range.to]);
 useEffect(()=>{void load()},[load]);
 async function create(){
  const amount=Math.round(Number(price.replace(",","."))*100),student=students.find(x=>x.id===studentId),group=groups.find(x=>x.id===groupId);
  if((lessonType==="individual"&&!student)||(lessonType==="group"&&!group)||!Number.isFinite(amount)||amount<0){Alert.alert("חסרים פרטים",lessonType==="group"?"בחרי קבוצה והזיני מחיר תקין.":"בחרי תלמיד והזיני מחיר תקין.");return;}
  setBusy(true);try{const input={title:title.trim()||(lessonType==="group"?`שיעור קבוצתי · ${group?.name??""}`:`שיעור עם ${student?.displayName??""}`),startsOn:date,localStartTime:time,durationMinutes:60,recurrenceIntervalWeeks:interval,endsOn:endDate||undefined,defaultPriceAgorot:amount,parentReminderMinutes,studentReminderMinutes};if(lessonType==="group"&&group)await createCloudGroupLessonSeries(businessId,{...input,groupId:group.id});else if(student)await createCloudLessonSeries(businessId,{...input,studentId:student.id});setStudentId(null);setGroupId(null);setDate(today());setTime("16:30");setPrice("");setEndDate("");await load();Alert.alert("נשמר","השיעורים נוספו ליומן המשותף ומופיעים גם ב־Windows.");}catch(e){Alert.alert("יצירת השיעורים נכשלה",e instanceof Error?e.message:"נסי שוב")}finally{setBusy(false)}
 }
 async function update(item:CloudLessonItem,attendance:CloudLessonItem["attendance"],payment:CloudLessonItem["payment"]){setBusy(true);try{await updateCloudLessonParticipant(businessId,item,attendance,payment,payment==="paid"?"bit":null);await load()}catch(e){Alert.alert("עדכון השיעור נכשל",e instanceof Error?e.message:"נסי שוב")}finally{setBusy(false)}}
 function openNotes(item:CloudLessonItem){setNotesTarget(item);setSummary(item.summary??"");setHomework(item.homework??"");}
 async function saveNotes(){if(!notesTarget)return;setBusy(true);try{await saveCloudLessonNotes(businessId,notesTarget.lessonId,summary,homework);setNotesTarget(null);await load()}catch(e){Alert.alert("שמירת הסיכום נכשלה",e instanceof Error?e.message:"נסי שוב")}finally{setBusy(false)}}
 return <ScrollView contentContainerStyle={s.content} refreshControl={<RefreshControl refreshing={busy} onRefresh={()=>void load()}/>} keyboardShouldPersistTaps="handled">
  <Text style={s.eyebrow}>יומן משותף</Text><Text style={s.title}>השיעורים שלי</Text><Text style={s.subtitle}>קביעת שיעור כאן מופיעה גם בתוכנת Windows.</Text>
  <View style={s.card}><Text style={s.cardTitle}>שיעור קבוע חדש</Text><View style={s.row}><Pressable style={[s.interval,lessonType==="individual"&&s.intervalActive]} onPress={()=>setLessonType("individual")}><Text style={lessonType==="individual"?s.intervalActiveText:s.intervalText}>שיעור אישי</Text></Pressable><Pressable style={[s.interval,lessonType==="group"&&s.intervalActive]} onPress={()=>setLessonType("group")}><Text style={lessonType==="group"?s.intervalActiveText:s.intervalText}>שיעור קבוצתי</Text></Pressable></View><Text style={s.label}>{lessonType==="group"?"בחירת קבוצה":"בחירת תלמיד"}</Text><View style={s.chips}>{lessonType==="group"?groups.map(group=><Pressable key={group.id} onPress={()=>setGroupId(group.id)} style={[s.chip,groupId===group.id&&s.chipActive]}><Text style={groupId===group.id?s.chipActiveText:s.chipText}>{group.name} · {group.members.length}</Text></Pressable>):students.map(student=><Pressable key={student.id} onPress={()=>setStudentId(student.id)} style={[s.chip,studentId===student.id&&s.chipActive]}><Text style={studentId===student.id?s.chipActiveText:s.chipText}>{student.displayName}</Text></Pressable>)}</View>
   <TextInput style={s.input} value={title} onChangeText={setTitle} maxLength={160} placeholder="כותרת השיעור" textAlign="right"/>
   <View style={s.row}><TextInput style={[s.input,s.half]} value={date} onChangeText={setDate} maxLength={10} placeholder="YYYY-MM-DD" textAlign="center"/><TextInput style={[s.input,s.half]} value={time} onChangeText={setTime} maxLength={5} placeholder="HH:MM" textAlign="center"/></View>
   <TextInput style={s.input} value={price} onChangeText={setPrice} maxLength={12} keyboardType="decimal-pad" placeholder="מחיר שיעור ₪" textAlign="right"/>
   <View style={s.row}><Pressable style={[s.interval,interval===1&&s.intervalActive]} onPress={()=>setInterval(1)}><Text style={interval===1?s.intervalActiveText:s.intervalText}>כל שבוע</Text></Pressable><Pressable style={[s.interval,interval===2&&s.intervalActive]} onPress={()=>setInterval(2)}><Text style={interval===2?s.intervalActiveText:s.intervalText}>כל שבועיים</Text></Pressable></View>
   <Text style={s.label}>תזכורת להורה</Text><View style={s.chips}>{reminderOptions.map(minutes=><Pressable key={`parent-${minutes}`} onPress={()=>setParentReminderMinutes(minutes)} style={[s.chip,parentReminderMinutes===minutes&&s.chipActive]}><Text style={parentReminderMinutes===minutes?s.chipActiveText:s.chipText}>{reminderLabel(minutes)}</Text></Pressable>)}</View>
   <Text style={s.label}>תזכורת לתלמיד</Text><View style={s.chips}>{reminderOptions.map(minutes=><Pressable key={`student-${minutes}`} onPress={()=>setStudentReminderMinutes(minutes)} style={[s.chip,studentReminderMinutes===minutes&&s.chipActive]}><Text style={studentReminderMinutes===minutes?s.chipActiveText:s.chipText}>{reminderLabel(minutes)}</Text></Pressable>)}</View>
   <TextInput style={s.input} value={endDate} onChangeText={setEndDate} maxLength={10} placeholder="תאריך סיום (לא חובה) YYYY-MM-DD" textAlign="center"/>
   <Pressable style={s.primary} disabled={busy||(lessonType==="group"?!groups.length:!students.length)} onPress={()=>void create()}><Text style={s.primaryText}>הוספה ליומן</Text></Pressable>
  </View>
  <Text style={s.listTitle}>ארבעת השבועות הקרובים</Text>
  {items.map(item=><View key={item.participantId} style={s.item}><View style={{flex:1}}><Text style={s.itemTitle}>{item.studentName}</Text><Text style={s.meta}>{dateTime(item.startsAt)} · {item.title}{item.kind==="group"?" · קבוצתי":""}</Text><Text style={s.amount}>{money(item.amountAgorot)} · {item.payment==="paid"?"שולם":"טרם שולם"}</Text>{item.summary?<Text style={s.note}>סיכום: {item.summary}</Text>:null}</View><View style={s.actions}><Pressable style={s.small} onPress={()=>void update(item,"attended",item.payment)}><Text style={s.smallText}>הגיע</Text></Pressable><Pressable style={s.small} onPress={()=>void update(item,"absent",item.payment)}><Text style={s.smallText}>נעדר</Text></Pressable><Pressable style={s.small} onPress={()=>void update(item,item.attendance,"paid")}><Text style={s.smallText}>שולם</Text></Pressable><Pressable onPress={()=>openNotes(item)}><Text style={s.notesAction}>סיכום</Text></Pressable></View></View>)}
  {!busy&&!items.length?<View style={s.empty}><Text style={s.meta}>אין שיעורים מתוכננים בארבעת השבועות הקרובים.</Text></View>:null}
  {notesTarget?<View style={s.card}><Text style={s.cardTitle}>סיכום שיעור · {notesTarget.studentName}</Text><TextInput style={[s.input,s.notes]} value={summary} onChangeText={setSummary} multiline placeholder="מה עשינו בשיעור?" textAlign="right" textAlignVertical="top"/><TextInput style={[s.input,s.notes]} value={homework} onChangeText={setHomework} multiline placeholder="משימה להמשך" textAlign="right" textAlignVertical="top"/><View style={s.row}><Pressable style={[s.primary,s.half]} disabled={busy} onPress={()=>void saveNotes()}><Text style={s.primaryText}>שמירת סיכום</Text></Pressable><Pressable style={[s.secondary,s.half]} onPress={()=>setNotesTarget(null)}><Text style={s.secondaryText}>ביטול</Text></Pressable></View></View>:null}
 </ScrollView>;
}

const s=StyleSheet.create({content:{padding:18,paddingBottom:120,gap:12,direction:"rtl"},eyebrow:{textAlign:"right",fontWeight:"900",color:theme.accentStrong},title:{textAlign:"right",fontSize:30,fontWeight:"900",color:theme.text},subtitle:{textAlign:"right",fontSize:13,color:theme.muted,lineHeight:20},card:{backgroundColor:theme.surface,borderRadius:theme.radius,padding:17,gap:10,borderWidth:1,borderColor:theme.border},cardTitle:{textAlign:"right",fontSize:18,fontWeight:"900",color:theme.text},label:{textAlign:"right",fontWeight:"700",color:theme.text},chips:{flexDirection:"row-reverse",flexWrap:"wrap",gap:7},chip:{borderWidth:1,borderColor:theme.border,borderRadius:14,paddingVertical:9,paddingHorizontal:11,backgroundColor:"#FBFCFF"},chipActive:{backgroundColor:theme.primary,borderColor:theme.primary},chipText:{color:theme.text,fontWeight:"700"},chipActiveText:{color:"#fff",fontWeight:"800"},input:{backgroundColor:"#FBFCFF",borderWidth:1,borderColor:theme.border,borderRadius:15,padding:12,color:theme.text},row:{flexDirection:"row-reverse",gap:8},half:{flex:1},interval:{flex:1,alignItems:"center",padding:12,borderRadius:14,backgroundColor:"#EDF3FA"},intervalActive:{backgroundColor:theme.primary},intervalText:{color:theme.text,fontWeight:"700"},intervalActiveText:{color:"#fff",fontWeight:"800"},primary:{backgroundColor:theme.accent,borderRadius:15,padding:14,alignItems:"center"},primaryText:{color:theme.navy,fontWeight:"900"},secondary:{borderWidth:1,borderColor:theme.border,borderRadius:15,padding:14,alignItems:"center"},secondaryText:{color:theme.text,fontWeight:"800"},listTitle:{textAlign:"right",fontSize:19,fontWeight:"900",color:theme.text,marginTop:8},item:{backgroundColor:theme.surface,borderWidth:1,borderColor:theme.border,borderRadius:18,padding:15,flexDirection:"row-reverse",gap:12},itemTitle:{textAlign:"right",fontWeight:"900",fontSize:16,color:theme.text},meta:{textAlign:"right",fontSize:12,color:theme.muted,marginTop:3},amount:{textAlign:"right",fontWeight:"800",color:theme.primary,marginTop:5},note:{textAlign:"right",fontSize:12,color:theme.text,marginTop:5},actions:{alignItems:"flex-end",gap:6},small:{paddingVertical:6,paddingHorizontal:8,borderRadius:9,backgroundColor:theme.primarySoft},smallText:{color:theme.primary,fontWeight:"800",fontSize:11},notesAction:{color:theme.accentStrong,fontWeight:"900",fontSize:12},empty:{padding:22,alignItems:"center"},notes:{minHeight:76}});
