import React,{useCallback,useEffect,useState} from "react";
import {Alert,Pressable,RefreshControl,ScrollView,StyleSheet,Text,TextInput,View} from "react-native";
import type {CloudStudent} from "../data/supabase/StudentCloudRepository";
import {archiveCloudStudentGroup,listCloudStudentGroups,saveCloudStudentGroup,type CloudStudentGroup} from "../data/supabase/GroupCloudRepository";
import {theme} from "../theme/theme";

export function CloudGroupsPanel({businessId,students}:{businessId:string;students:CloudStudent[]}){
 const [groups,setGroups]=useState<CloudStudentGroup[]>([]),[busy,setBusy]=useState(false),[editing,setEditing]=useState<CloudStudentGroup|null>(null),[name,setName]=useState(""),[description,setDescription]=useState(""),[memberIds,setMemberIds]=useState<string[]>([]);
 const load=useCallback(async()=>{setBusy(true);try{setGroups(await listCloudStudentGroups(businessId))}catch(e){Alert.alert("טעינת קבוצות נכשלה",e instanceof Error?e.message:"נסי שוב")}finally{setBusy(false)}},[businessId]);
 useEffect(()=>{void load()},[load]);
 const reset=()=>{setEditing(null);setName("");setDescription("");setMemberIds([])};
 const edit=(group:CloudStudentGroup)=>{setEditing(group);setName(group.name);setDescription(group.description??"");setMemberIds(group.memberIds)};
 const toggle=(id:string)=>setMemberIds(ids=>ids.includes(id)?ids.filter(item=>item!==id):[...ids,id]);
 const save=async()=>{setBusy(true);try{await saveCloudStudentGroup(businessId,{id:editing?.id,name,description,studentIds:memberIds});reset();await load();Alert.alert("נשמר","הקבוצה מעודכנת גם ב־Windows.")}catch(e){Alert.alert("שמירת קבוצה נכשלה",e instanceof Error?e.message:"נסי שוב")}finally{setBusy(false)}};
 const archive=(group:CloudStudentGroup)=>Alert.alert("הסתרת קבוצה",`להסתיר את ${group.name}?`,[{text:"ביטול",style:"cancel"},{text:"הסתר",style:"destructive",onPress:()=>void (async()=>{setBusy(true);try{await archiveCloudStudentGroup(businessId,group.id);await load()}catch(e){Alert.alert("לא ניתן להסתיר",e instanceof Error?e.message:"נסי שוב")}finally{setBusy(false)}})()}]);
 return <ScrollView contentContainerStyle={s.content} refreshControl={<RefreshControl refreshing={busy} onRefresh={()=>void load()}/>} keyboardShouldPersistTaps="handled">
  <Text style={s.eyebrow}>ניהול קבוצות בענן</Text><Text style={s.title}>הקבוצות שלי</Text><Text style={s.subtitle}>כל שינוי נשמר בענן המשותף ומופיע גם בתוכנת Windows.</Text>
  <View style={s.card}><Text style={s.cardTitle}>{editing?"עריכת קבוצה":"קבוצה חדשה"}</Text><TextInput style={s.input} value={name} onChangeText={setName} maxLength={160} placeholder="שם הקבוצה" textAlign="right"/><TextInput style={[s.input,s.notes]} value={description} onChangeText={setDescription} maxLength={2000} placeholder="תיאור הקבוצה (לא חובה)" multiline textAlign="right" textAlignVertical="top"/><Text style={s.label}>חברי הקבוצה</Text><View style={s.chips}>{students.map(student=><Pressable key={student.id} onPress={()=>toggle(student.id)} style={[s.chip,memberIds.includes(student.id)&&s.chipActive]}><Text style={memberIds.includes(student.id)?s.chipActiveText:s.chipText}>{student.displayName}</Text></Pressable>)}</View><View style={s.row}><Pressable style={[s.primary,s.half]} onPress={()=>void save()} disabled={busy}><Text style={s.primaryText}>{editing?"שמירת שינויים":"יצירת קבוצה"}</Text></Pressable>{editing?<Pressable style={[s.secondary,s.half]} onPress={reset}><Text style={s.secondaryText}>ביטול</Text></Pressable>:null}</View></View>
  {groups.map(group=><View key={group.id} style={s.item}><View style={{flex:1}}><Text style={s.itemTitle}>{group.name}</Text>{group.description?<Text style={s.meta}>{group.description}</Text>:null}<Text style={s.members}>{group.members.length?group.members.map(member=>member.displayName).join(" · "):"אין חברים פעילים"}</Text></View><View style={s.actions}><Pressable onPress={()=>edit(group)}><Text style={s.edit}>עריכה</Text></Pressable><Pressable onPress={()=>archive(group)}><Text style={s.archive}>הסתרה</Text></Pressable></View></View>)}
  {!busy&&!groups.length?<View style={s.empty}><Text style={s.meta}>עדיין אין קבוצות בענן.</Text></View>:null}
 </ScrollView>;
}
const s=StyleSheet.create({content:{padding:18,paddingBottom:120,gap:12,direction:"rtl"},eyebrow:{textAlign:"right",fontWeight:"900",color:theme.accentStrong},title:{textAlign:"right",fontSize:30,fontWeight:"900",color:theme.text},subtitle:{textAlign:"right",fontSize:13,color:theme.muted,lineHeight:20},card:{backgroundColor:theme.surface,borderRadius:theme.radius,padding:17,gap:10,borderWidth:1,borderColor:theme.border},cardTitle:{textAlign:"right",fontSize:18,fontWeight:"900",color:theme.text},label:{textAlign:"right",fontWeight:"800",color:theme.text},input:{backgroundColor:"#FBFCFF",borderWidth:1,borderColor:theme.border,borderRadius:15,padding:12,color:theme.text},notes:{minHeight:70},chips:{flexDirection:"row-reverse",flexWrap:"wrap",gap:7},chip:{borderWidth:1,borderColor:theme.border,borderRadius:14,paddingVertical:9,paddingHorizontal:11,backgroundColor:"#FBFCFF"},chipActive:{backgroundColor:theme.primary,borderColor:theme.primary},chipText:{color:theme.text,fontWeight:"700"},chipActiveText:{color:"#fff",fontWeight:"800"},row:{flexDirection:"row-reverse",gap:8},half:{flex:1},primary:{backgroundColor:theme.accent,borderRadius:15,padding:14,alignItems:"center"},primaryText:{color:theme.navy,fontWeight:"900"},secondary:{borderWidth:1,borderColor:theme.border,borderRadius:15,padding:14,alignItems:"center"},secondaryText:{color:theme.text,fontWeight:"800"},item:{backgroundColor:theme.surface,borderWidth:1,borderColor:theme.border,borderRadius:18,padding:15,flexDirection:"row-reverse",gap:12},itemTitle:{textAlign:"right",fontWeight:"900",fontSize:16,color:theme.text},meta:{textAlign:"right",fontSize:12,color:theme.muted,marginTop:3},members:{textAlign:"right",fontSize:12,color:theme.primary,marginTop:8,fontWeight:"700"},actions:{alignItems:"flex-end",gap:9},edit:{color:theme.accentStrong,fontWeight:"800",fontSize:12},archive:{color:theme.danger,fontWeight:"800",fontSize:12},empty:{padding:22,alignItems:"center"}});
