import React,{useCallback,useEffect,useState} from "react";
import {Alert,Pressable,StyleSheet,Text,View} from "react-native";
import {theme} from "../theme/theme";
import {StudentLocalStore,type MobileLesson} from "./StudentLocalStore";
import {DeviceCalendarSyncService,type CalendarChoice,type DeviceCalendarStatus} from "./DeviceCalendarSyncService";

const snapshotOf=(items:MobileLesson[])=>JSON.stringify(items.map(x=>[x.id,x.title,x.startsAt,x.endsAt,x.cancelled,x.lessonSummary,x.homework,x.participants.map(p=>[p.studentId,p.attendance,p.payment,p.amountAgorot])]));

export function DeviceCalendarPanel({lessons}:{lessons:MobileLesson[]}){
 const[status,setStatus]=useState<DeviceCalendarStatus|null>(null),[choices,setChoices]=useState<CalendarChoice[]|null>(null),[working,setWorking]=useState(false),[lastSnapshot,setLastSnapshot]=useState("");
 const refresh=useCallback(async()=>{try{setStatus(await DeviceCalendarSyncService.getStatus())}catch{}},[]);
 useEffect(()=>{void refresh()},[refresh]);
 async function connect(){setWorking(true);try{const list=await DeviceCalendarSyncService.requestCalendars();setChoices(list);if(!list.length)Alert.alert("לא נמצא יומן","לא נמצא במכשיר יומן שניתן לעריכה.");}catch(e){Alert.alert("גישה ליומן",e instanceof Error&&e.message==="CALENDAR_PERMISSION_DENIED"?"יש לאשר גישה ליומן כדי לסנכרן שיעורים.":"לא ניתן לקרוא את יומני המכשיר.")}finally{setWorking(false)}}
 async function select(choice:CalendarChoice){setWorking(true);try{setStatus(await DeviceCalendarSyncService.selectCalendar(choice.id));setChoices(null);await syncNow()}catch{Alert.alert("לא ניתן לבחור יומן","היומן שבחרת אינו זמין לעריכה.")}finally{setWorking(false)}}
 async function syncNow(){setWorking(true);try{const current=await StudentLocalStore.listLessons();const result=await DeviceCalendarSyncService.sync(current);setLastSnapshot(snapshotOf(current));await refresh();if(result.failed)Alert.alert("הסנכרון הסתיים",`${result.created} נוספו, ${result.updated} עודכנו, ${result.deleted} הוסרו, ${result.failed} לא סונכרנו.`);}catch(e){Alert.alert("סנכרון יומן",e instanceof Error&&e.message==="CALENDAR_PERMISSION_DENIED"?"הרשאת היומן אינה פעילה.":"לא ניתן לסנכרן את היומן כרגע.")}finally{setWorking(false)}}
 async function disconnect(){setWorking(true);try{setStatus(await DeviceCalendarSyncService.disconnect());setChoices(null);setLastSnapshot("")}finally{setWorking(false)}}
 useEffect(()=>{if(!status?.calendarId||status.permission!=="granted"||working)return;const snapshot=snapshotOf(lessons);if(!snapshot||snapshot===lastSnapshot)return;const timer=setTimeout(()=>{void syncNow()},1200);return()=>clearTimeout(timer)},[lessons,status?.calendarId,status?.permission,lastSnapshot,working]);
 return <View style={s.card}><View style={s.top}><View style={s.text}><Text style={s.title}>{status?.calendarId?"יומן מסונכרן":"סנכרון ליומן"}</Text><Text style={s.sub}>{status?.calendarId?`${status.isGoogle?"Google · ":""}${status.calendarTitle??"יומן המכשיר"}${status.lastSyncAt?` · עודכן ${new Intl.DateTimeFormat("he-IL",{hour:"2-digit",minute:"2-digit"}).format(new Date(status.lastSyncAt))}`:""}`:"בחרי יומן מהמכשיר. יומן Google המחובר לטלפון יסונכרן דרך Android."}</Text></View><Text style={status?.calendarId?s.ok:s.off}>{status?.calendarId?"●":"○"}</Text></View>
 {choices&&<View style={s.choices}>{choices.map(c=><Pressable key={c.id} style={s.choice} onPress={()=>void select(c)}><Text style={s.choiceTitle}>{c.isGoogle?"G  ":""}{c.title}</Text><Text style={s.choiceSub}>{c.sourceName||c.sourceType||"יומן במכשיר"}{c.isPrimary?" · ראשי":""}</Text></Pressable>)}</View>}
 <View style={s.actions}>{!status?.calendarId?<Pressable disabled={working} style={s.primary} onPress={()=>void connect()}><Text style={s.primaryText}>{working?"טוען יומנים…":"חבר יומן"}</Text></Pressable>:<><Pressable disabled={working} style={s.primary} onPress={()=>void syncNow()}><Text style={s.primaryText}>{working?"מסנכרן…":"סנכרן עכשיו"}</Text></Pressable><Pressable disabled={working} style={s.secondary} onPress={()=>void disconnect()}><Text style={s.secondaryText}>נתק</Text></Pressable></>}</View>
 </View>;
}
const s=StyleSheet.create({card:{backgroundColor:theme.surface,borderRadius:theme.radius,padding:14,gap:12,borderWidth:1,borderColor:theme.border},top:{flexDirection:"row-reverse",justifyContent:"space-between",alignItems:"flex-start",gap:10},text:{flex:1},title:{fontWeight:"800",fontSize:16,color:theme.text,textAlign:"right"},sub:{fontSize:12,lineHeight:18,color:theme.muted,textAlign:"right",marginTop:3},ok:{color:"#15803d",fontSize:20},off:{color:theme.muted,fontSize:20},choices:{gap:7},choice:{padding:10,borderRadius:11,borderWidth:1,borderColor:theme.border,backgroundColor:theme.background},choiceTitle:{fontWeight:"800",color:theme.text,textAlign:"right"},choiceSub:{fontSize:11,color:theme.muted,textAlign:"right",marginTop:2},actions:{flexDirection:"row-reverse",gap:8},primary:{flex:1,backgroundColor:theme.primary,paddingVertical:10,borderRadius:11},primaryText:{color:"white",fontWeight:"800",textAlign:"center"},secondary:{paddingVertical:10,paddingHorizontal:18,borderRadius:11,borderWidth:1,borderColor:theme.border},secondaryText:{color:theme.text,fontWeight:"700"}});
