import React,{useCallback,useEffect,useState} from "react";
import {Alert,Pressable,StyleSheet,Text,View} from "react-native";
import {theme} from "../theme/theme";
import type {MobileLesson,MobileStudent} from "./StudentLocalStore";
import {ReminderLocalStore,type ReminderAudience,type ReminderConfig,type ReminderEntry} from "./ReminderLocalStore";

const audienceLabels:Record<ReminderAudience,string>={student:"לתלמיד",guardian:"להורה",both:"לשניהם"};
const leadLabels:Record<ReminderConfig["leadMinutes"],string>={60:"שעה לפני",180:"3 שעות לפני",1440:"יום לפני"};
const statusLabels:Record<ReminderEntry["status"],string>={scheduled:"מתוזמנת",ready:"מוכנה",test_sent:"נשלחה בבדיקה",failed:"נכשלה בבדיקה"};
const dt=(v:string)=>new Intl.DateTimeFormat("he-IL",{dateStyle:"short",timeStyle:"short"}).format(new Date(v));

export function ReminderSimulationPanel({lessons,students}:{lessons:MobileLesson[];students:MobileStudent[]}){
 const[config,setConfig]=useState<ReminderConfig>({enabled:false,audience:"guardian",leadMinutes:1440}),[entries,setEntries]=useState<ReminderEntry[]>([]),[busy,setBusy]=useState(false);
 const refresh=useCallback(async()=>{const[c,e]=await Promise.all([ReminderLocalStore.getConfig(),ReminderLocalStore.list()]);setConfig(c);setEntries(e)},[]);
 useEffect(()=>{void refresh()},[refresh]);
 useEffect(()=>{if(!config.enabled)return;let cancelled=false;const timer=setTimeout(()=>{void ReminderLocalStore.syncPlan(lessons,students).then(next=>{if(!cancelled)setEntries(next)}).catch(()=>{})},250);return()=>{cancelled=true;clearTimeout(timer)}},[lessons,students,config.enabled,config.audience,config.leadMinutes]);
 async function save(next:ReminderConfig){setBusy(true);try{await ReminderLocalStore.saveConfig(next);setConfig(next);if(next.enabled){setEntries(await ReminderLocalStore.syncPlan(lessons,students));}else{setEntries(await ReminderLocalStore.list());}}finally{setBusy(false)}}
 async function rebuild(){setBusy(true);try{setEntries(await ReminderLocalStore.syncPlan(lessons,students))}catch(e){Alert.alert("תזכורות",e instanceof Error?e.message:"לא ניתן להכין תזכורות.")}finally{setBusy(false)}}
 async function act(entry:ReminderEntry,mode:"send"|"fail"|"retry"){setBusy(true);try{if(mode==="send")await ReminderLocalStore.simulateSend(entry.id);else if(mode==="fail")await ReminderLocalStore.simulateFailure(entry.id);else await ReminderLocalStore.retry(entry.id);setEntries(await ReminderLocalStore.list())}catch(e){Alert.alert("תזכורת",e instanceof Error?e.message:"הפעולה נכשלה.")}finally{setBusy(false)}}
 const visible=entries.slice(0,20);
 return <View style={s.card}><View style={s.top}><View style={s.flex}><Text style={s.title}>תזכורות לתלמיד ולהורה</Text><Text style={s.sub}>מצב בדיקה בלבד — אין WhatsApp, SMS או שליחה חיצונית.</Text></View><Text style={config.enabled?s.on:s.off}>{config.enabled?"● פעיל":"○ כבוי"}</Text></View>
 <View style={s.row}><Pressable disabled={busy} style={[s.toggle,config.enabled&&s.toggleActive]} onPress={()=>void save({...config,enabled:!config.enabled})}><Text style={config.enabled?s.toggleTextActive:s.toggleText}>{config.enabled?"כבה תזכורות":"הפעל תזכורות"}</Text></Pressable><Pressable disabled={busy||!config.enabled} style={s.secondary} onPress={()=>void rebuild()}><Text style={s.secondaryText}>רענן תכנון</Text></Pressable></View>
 <Text style={s.label}>למי לשלוח</Text><View style={s.chips}>{(["student","guardian","both"] as ReminderAudience[]).map(v=><Pressable key={v} disabled={busy} onPress={()=>void save({...config,audience:v})} style={[s.chip,config.audience===v&&s.chipActive]}><Text style={config.audience===v?s.chipTextActive:s.chipText}>{audienceLabels[v]}</Text></Pressable>)}</View>
 <Text style={s.label}>כמה זמן לפני השיעור</Text><View style={s.chips}>{([60,180,1440] as ReminderConfig["leadMinutes"][]).map(v=><Pressable key={v} disabled={busy} onPress={()=>void save({...config,leadMinutes:v})} style={[s.chip,config.leadMinutes===v&&s.chipActive]}><Text style={config.leadMinutes===v?s.chipTextActive:s.chipText}>{leadLabels[v]}</Text></Pressable>)}</View>
 <View style={s.historyHead}><Text style={s.historyTitle}>היסטוריית תזכורות</Text><Text style={s.count}>{entries.length}</Text></View>
 {!visible.length?<Text style={s.empty}>אין עדיין תזכורות מתוכננות.</Text>:visible.map(entry=><View key={entry.id} style={s.entry}><View style={s.entryTop}><View style={s.flex}><Text style={s.entryTitle}>{entry.recipient==="guardian"?"הורה":"תלמיד"} · {entry.recipientName}</Text><Text style={s.meta}>{dt(entry.scheduledFor)} · {statusLabels[entry.status]} · ניסיון {entry.attemptCount}</Text></View><Text style={entry.status==="failed"?s.failed:entry.status==="test_sent"?s.sent:s.pending}>{statusLabels[entry.status]}</Text></View><Text style={s.message}>{entry.message}</Text>{entry.lastError?<Text style={s.error}>{entry.lastError}</Text>:null}<View style={s.actions}>{entry.status==="failed"?<Pressable disabled={busy} style={s.action} onPress={()=>void act(entry,"retry")}><Text style={s.actionText}>נסה שוב</Text></Pressable>:<><Pressable disabled={busy} style={s.action} onPress={()=>void act(entry,"send")}><Text style={s.actionText}>דמה הצלחה</Text></Pressable><Pressable disabled={busy} style={s.action} onPress={()=>void act(entry,"fail")}><Text style={s.actionText}>דמה כשל</Text></Pressable></>}</View></View>)}
 </View>;
}
const s=StyleSheet.create({card:{backgroundColor:theme.surface,borderRadius:theme.radius,padding:14,gap:10,borderWidth:1,borderColor:theme.border},top:{flexDirection:"row-reverse",alignItems:"flex-start",justifyContent:"space-between",gap:10},flex:{flex:1},title:{fontSize:16,fontWeight:"800",color:theme.text,textAlign:"right"},sub:{fontSize:12,color:theme.muted,textAlign:"right",marginTop:3,lineHeight:18},on:{color:"#166534",fontWeight:"800"},off:{color:theme.muted,fontWeight:"800"},row:{flexDirection:"row-reverse",gap:8},toggle:{flex:1,borderWidth:1,borderColor:theme.border,borderRadius:11,paddingVertical:10,backgroundColor:"white"},toggleActive:{backgroundColor:theme.primary,borderColor:theme.primary},toggleText:{textAlign:"center",fontWeight:"800",color:theme.text},toggleTextActive:{textAlign:"center",fontWeight:"800",color:"white"},secondary:{paddingHorizontal:14,paddingVertical:10,borderRadius:11,borderWidth:1,borderColor:theme.border},secondaryText:{fontWeight:"700",color:theme.text},label:{textAlign:"right",fontSize:12,fontWeight:"700",color:theme.muted},chips:{flexDirection:"row-reverse",flexWrap:"wrap",gap:7},chip:{paddingVertical:7,paddingHorizontal:10,borderWidth:1,borderColor:theme.border,borderRadius:999,backgroundColor:"white"},chipActive:{backgroundColor:theme.primary,borderColor:theme.primary},chipText:{color:theme.text,fontWeight:"600"},chipTextActive:{color:"white",fontWeight:"800"},historyHead:{flexDirection:"row-reverse",justifyContent:"space-between",alignItems:"center",marginTop:4},historyTitle:{fontSize:14,fontWeight:"800",color:theme.text},count:{fontSize:12,fontWeight:"800",color:theme.primary},empty:{textAlign:"right",fontSize:12,color:theme.muted},entry:{borderTopWidth:1,borderTopColor:theme.border,paddingTop:10,gap:6},entryTop:{flexDirection:"row-reverse",justifyContent:"space-between",alignItems:"flex-start",gap:8},entryTitle:{fontSize:13,fontWeight:"800",color:theme.text,textAlign:"right"},meta:{fontSize:11,color:theme.muted,textAlign:"right",marginTop:2},pending:{fontSize:11,fontWeight:"800",color:"#92400e"},sent:{fontSize:11,fontWeight:"800",color:"#166534"},failed:{fontSize:11,fontWeight:"800",color:"#b91c1c"},message:{fontSize:12,lineHeight:18,color:theme.text,textAlign:"right",backgroundColor:theme.background,padding:8,borderRadius:9},error:{fontSize:11,color:"#b91c1c",textAlign:"right"},actions:{flexDirection:"row-reverse",gap:6},action:{borderWidth:1,borderColor:theme.border,borderRadius:9,paddingVertical:7,paddingHorizontal:10,backgroundColor:"white"},actionText:{fontSize:11,fontWeight:"700",color:theme.text}});
