import type {SupabaseCloudService} from "./SupabaseCloudService";
import type {StudentRecord} from "../../../../packages/database/src/studentTypes";
import type {StudentGroupSaveInput,StudentGroupWithMembers} from "../../../../packages/database/src/groupTypes";

function mapStudent(r:any):StudentRecord{return{id:String(r.id),businessId:String(r.business_id),displayName:String(r.display_name??""),phone:r.phone?String(r.phone):null,email:r.email?String(r.email):null,schoolName:r.school_name?String(r.school_name):null,schoolGrade:r.school_grade?String(r.school_grade):null,focusNotes:r.focus_notes?String(r.focus_notes):null,defaultPriceAgorot:Number(r.default_price_agorot??0),payerCustomerId:r.payer_customer_id?String(r.payer_customer_id):null,reminderEnabled:Boolean(r.reminder_enabled),active:Boolean(r.active),createdAt:String(r.created_at??""),updatedAt:String(r.updated_at??"")};}
export class GroupManagementCloudService{
 constructor(private readonly cloud:SupabaseCloudService){}
 private businessId():string{const s=this.cloud.getStatus();if(!s.connected||!s.businessId)throw new Error("CLOUD_CONNECTION_REQUIRED_FOR_GROUPS");return s.businessId;}
 async list():Promise<StudentGroupWithMembers[]>{const businessId=this.businessId(),client=this.cloud.getClient();const{data:groups,error}=await client.from("student_groups").select("id,business_id,name,description,active,created_at,updated_at").eq("business_id",businessId).eq("active",true).order("name");if(error)throw new Error(`CLOUD_GROUP_LIST_FAILED:${error.message}`);if(!(groups??[]).length)return[];const ids=(groups??[]).map((g:any)=>String(g.id));const{data:members,error:me}=await client.from("student_group_members").select("group_id,student_id").eq("business_id",businessId).in("group_id",ids).is("left_at",null);if(me)throw new Error(`CLOUD_GROUP_MEMBERS_FAILED:${me.message}`);const studentIds=[...new Set((members??[]).map((m:any)=>String(m.student_id)))];let students:any[]=[];if(studentIds.length){const r=await client.from("students").select("id,business_id,display_name,phone,email,school_name,school_grade,focus_notes,default_price_agorot,payer_customer_id,reminder_enabled,active,created_at,updated_at").eq("business_id",businessId).in("id",studentIds);if(r.error)throw new Error(`CLOUD_GROUP_STUDENTS_FAILED:${r.error.message}`);students=r.data??[];}const sm=new Map(students.map(r=>[String(r.id),mapStudent(r)])),byGroup=new Map<string,StudentRecord[]>();for(const m of members??[]){const s=sm.get(String(m.student_id));if(s){const a=byGroup.get(String(m.group_id))??[];a.push(s);byGroup.set(String(m.group_id),a)}}return(groups??[]).map((g:any)=>({id:String(g.id),businessId:String(g.business_id),name:String(g.name),description:g.description?String(g.description):null,active:Boolean(g.active),createdAt:String(g.created_at),updatedAt:String(g.updated_at),members:byGroup.get(String(g.id))??[]}));}
 async save(input:StudentGroupSaveInput):Promise<StudentGroupWithMembers>{const businessId=this.businessId(),client=this.cloud.getClient(),name=input.name.trim(),description=(input.description??"").trim();if(name.length<2||name.length>160||description.length>2000)throw new Error("INVALID_GROUP");const ids=[...new Set(input.studentIds.filter(Boolean))];if(!ids.length)throw new Error("GROUP_REQUIRES_MEMBER");const check=await client.from("students").select("id").eq("business_id",businessId).eq("active",true).in("id",ids);if(check.error||(check.data??[]).length!==ids.length)throw new Error("GROUP_MEMBER_NOT_FOUND");let groupId=input.id; if(groupId){const u=await client.from("student_groups").update({name,description:description||null,updated_at:new Date().toISOString()}).eq("business_id",businessId).eq("id",groupId).select("id").single();if(u.error)throw new Error(`CLOUD_GROUP_SAVE_FAILED:${u.error.message}`);}else{const i=await client.from("student_groups").insert({business_id:businessId,name,description:description||null,active:true}).select("id").single();if(i.error||!i.data)throw new Error(`CLOUD_GROUP_SAVE_FAILED:${i.error?.message??"EMPTY"}`);groupId=String(i.data.id);}const current=await client.from("student_group_members").select("student_id").eq("business_id",businessId).eq("group_id",groupId).is("left_at",null);if(current.error)throw new Error(`CLOUD_GROUP_MEMBERS_FAILED:${current.error.message}`);const currentIds=new Set((current.data??[]).map((x:any)=>String(x.student_id))),wanted=new Set(ids),now=new Date().toISOString();const remove=[...currentIds].filter(x=>!wanted.has(x)),add=ids.filter(x=>!currentIds.has(x));if(remove.length){const r=await client.from("student_group_members").update({left_at:now}).eq("business_id",businessId).eq("group_id",groupId).in("student_id",remove).is("left_at",null);if(r.error)throw new Error(`CLOUD_GROUP_MEMBER_REMOVE_FAILED:${r.error.message}`);}for(const studentId of add){const existing=await client.from("student_group_members").select("student_id").eq("business_id",businessId).eq("group_id",groupId).eq("student_id",studentId).maybeSingle();if(existing.data){const r=await client.from("student_group_members").update({joined_at:now,left_at:null}).eq("business_id",businessId).eq("group_id",groupId).eq("student_id",studentId);if(r.error)throw new Error(`CLOUD_GROUP_MEMBER_REJOIN_FAILED:${r.error.message}`);}else{const r=await client.from("student_group_members").insert({business_id:businessId,group_id:groupId,student_id:studentId});if(r.error)throw new Error(`CLOUD_GROUP_MEMBER_ADD_FAILED:${r.error.message}`);}}const all=await this.list(),found=all.find(g=>g.id===groupId);if(!found)throw new Error("CLOUD_GROUP_SAVE_LOOKUP_FAILED");return found;}
 async deactivate(id:string):Promise<void>{const businessId=this.businessId();if(!id)throw new Error("INVALID_GROUP");const{error}=await this.cloud.getClient().from("student_groups").update({active:false,updated_at:new Date().toISOString()}).eq("business_id",businessId).eq("id",id);if(error)throw new Error(`CLOUD_GROUP_DEACTIVATE_FAILED:${error.message}`);}
}
