import {ipcMain,type IpcMainInvokeEvent} from "electron";
import type {SupabaseCloudService} from "../main/SupabaseCloudService";
import {LessonManagementCloudService} from "../main/LessonManagementCloudService";
import type {LessonSeriesSaveInput} from "../../../../packages/database/src/studentTypes";
import {apiFailure,apiSuccess,type ApiResult} from "../../../../packages/shared/src/api";
import {assertPayloadSize,assertTrustedSender,withTimeout} from "./security";

function lessonError(error:unknown):ApiResult<never>{const code=error instanceof Error?error.message:"UNKNOWN_ERROR";if(code==="UNTRUSTED_IPC_SENDER")return apiFailure("UNTRUSTED_IPC_SENDER","הבקשה נחסמה מטעמי אבטחה.",false);if(code.startsWith("INVALID_LESSON")||code==="LESSON_STUDENT_NOT_FOUND")return apiFailure("INVALID_INPUT","פרטי השיעור אינם תקינים.",false);if(code==="CLOUD_CONNECTION_REQUIRED_FOR_LESSONS")return apiFailure("DATABASE_OPERATION_FAILED","ניהול שיעורים דורש חיבור פעיל לחשבון הענן.",false);if(code==="OPERATION_TIMEOUT")return apiFailure("OPERATION_TIMEOUT","הפעולה ארכה זמן רב מדי והופסקה בבטחה.");return apiFailure("DATABASE_OPERATION_FAILED","לא ניתן להשלים את פעולת השיעורים. הנתונים הקיימים לא שונו.");}
async function handle<T>(event:IpcMainInvokeEvent,payload:unknown,action:()=>T|Promise<T>):Promise<ApiResult<T>>{try{assertTrustedSender(event);assertPayloadSize(payload);return apiSuccess(await withTimeout(Promise.resolve().then(action),30000));}catch(error){console.warn("[Lessons IPC] failure",error);return lessonError(error)}}
function parseSeries(raw:any):LessonSeriesSaveInput{return{studentId:typeof raw?.studentId==="string"?raw.studentId:"",title:typeof raw?.title==="string"?raw.title:"",weekday:Number(raw?.weekday) as 0|1|2|3|4|5|6,localStartTime:typeof raw?.localStartTime==="string"?raw.localStartTime:"",durationMinutes:Math.trunc(Number(raw?.durationMinutes)||0),recurrenceIntervalWeeks:Math.trunc(Number(raw?.recurrenceIntervalWeeks)||0),startsOn:typeof raw?.startsOn==="string"?raw.startsOn:"",endsOn:typeof raw?.endsOn==="string"?raw.endsOn:"",defaultPriceAgorot:Math.trunc(Number(raw?.defaultPriceAgorot)||0),parentReminderMinutes:Math.trunc(Number(raw?.parentReminderMinutes)||0),studentReminderMinutes:Math.trunc(Number(raw?.studentReminderMinutes)||0)};}
export function registerLessonHandlers(supabaseCloud:SupabaseCloudService):void{const lessons=new LessonManagementCloudService(supabaseCloud);ipcMain.handle("lessons:list-series",event=>handle(event,undefined,()=>lessons.listSeries()));ipcMain.handle("lessons:create-series",(event,input)=>handle(event,input,()=>lessons.createIndividualSeries(parseSeries(input))));ipcMain.handle("lessons:list-calendar",(event,input)=>handle(event,input,()=>lessons.listCalendar(typeof input?.fromIso==="string"?input.fromIso:"",typeof input?.toIso==="string"?input.toIso:"")));ipcMain.handle("lessons:update-participant",(event,input)=>handle(event,input,()=>lessons.updateParticipant(typeof input?.participantId==="string"?input.participantId:"",typeof input?.attendanceStatus==="string"?input.attendanceStatus:"",typeof input?.paymentStatus==="string"?input.paymentStatus:"",typeof input?.paymentMethod==="string"?input.paymentMethod:null,Math.trunc(Number(input?.amountAgorot)||0))));}
